### ISSUE TITLE
API for multi-threaded Souffle execution

### ISSUE THREAD

**Issue by csabahruska** [luc-tielen/souffle-haskell#1]
Souffle can run on multiple threads. The C++ API gives access to control the number of evaluation threads. Could you expose this functionality for Haskell?
```c++
void SouffleProgram::setNumThreads(std::size_t numThreadsValue);
```

**Comment by luc-tielen** [comment]
@csabahruska I added `setNumThreads` and `getNumThreads` to the API.
For this I had to point to souffle HEAD, and C++ version now needs to be C++17.
