### ISSUE TITLE
Compilation error of test suite on linux.

### ISSUE THREAD

**Issue by andorp** [luc-tielen/souffle-haskell#5]
I couldn't build and run the test suite on the linux. Changing the package.yaml did the trick.

![91347111_244078876634716_7890782201896239104_n](https://user-images.githubusercontent.com/3465327/77797956-47b75000-7072-11ea-80c6-c37b8b5e4c85.png)

@csabahruska thanks for the solution.

**Comment by andorp** [comment]
I will open a PR for this change.

**Comment by luc-tielen** [comment]
I think the `stdc++` vs `c++` is due to the C++ compiler that is used underneath to compile the C++ bits.
`c++` comes from libc++ (clang / llvm), while `stdc++` is for GCC.

Maybe a config flag needs to be added for compiler specific settings.

**Comment by luc-tielen** [comment]
I think you can do something similar to this: https://github.com/grin-compiler/idris-grin/blob/master/idris-grin.cabal#L60

Maybe this could work? (haven't tried yet)
```
if os(linux)
  extra-libraries: stdc++
if os(darwin)
  extra-libraries: c++
```

**Comment by luc-tielen** [comment]
CI has been setup for the project (which runs on Linux, see https://github.com/luc-tielen/souffle-haskell/pull/6). I managed to reproduce the error along the way and added a fix for it! It's weird that the place of `extra-libraries` is different between OS's and actually matters 🤔. 

Thank you for reporting this!
